# Generated by Django 3.0.5 on 2020-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('tym', models.DateTimeField(auto_now_add=True)),
                ('utym', models.DateTimeField(auto_now=True)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
